- name: gcr.io/cloud-builders/docker
  id: docker-build-push
  entrypoint: bash
  args:
  - '-c'
  - |
    cat Dockerfile
    docker build -t "gcr.io/acedemand-poc/master:1.0" .
    docker push "gcr.io/acedemand-poc/master:1.0"
