steps:
- name: gcr.io/cloud-builders/docker
  id: docker-build-push
  entrypoint: bash
  args:
  - '-c'
  - |
    cat Dockerfile
    docker build -t "gcr.io/pinaru-sandbox/hello-app1:1.0" .
    docker push "gcr.io/pinaru-sandbox/hello-app1:1.0"
